name: cors

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: [ production ]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: pm2 stop proxy
      - run: pm2 start proxy
